# This program is distributed under the terms of the GNU General Public License.
# For more details, see the LICENSE file in the root of the repository.

name: Non-Main Branch Push Checks

on:
    push:
        branches-ignore:
            - main

jobs:
    prevent-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check push branch
              run: |
                  if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                    echo "Error: Pushes from the main branch are not allowed." >&2
                    exit 1
                  fi
