name: Prevent pushes from main branch

on:
    push:
        branches-ignore:
            - main

jobs:
    prevent_pushes:
        runs-on: ubuntu-latest

        steps:
            - name: Check pushed branch
              run: |
                  if [ "$GITHUB_REF" = "refs/heads/main" ]; then
                    echo "Error: Pushes from the main branch are not allowed."
                    exit 1
                  fi
