# This program is distributed under the terms of the GNU General Public License.
# For more details, see the LICENSE file in the root of the repository.

name: Prevent Commits on Main Branch

on:
    push:
        branches:
            - main

jobs:
    prevent-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Check commit branch
              run: |
                  if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                    echo "Error: Commits to the main branch are not allowed." >&2
                    exit 1
                  fi
